// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpyAZMRo86SQvWLUGn0ubmhV6z2s7NUJc',
    appId: '1:347100845168:web:4dafb7a531f041af6e10b5',
    messagingSenderId: '347100845168',
    projectId: 'yosyelan-a2aae',
    authDomain: 'yosyelan-a2aae.firebaseapp.com',
    storageBucket: 'yosyelan-a2aae.appspot.com',
    measurementId: 'G-BCMXPCKVP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9y5J3NyfclQJd0Iu8i118xrDgbKT3wU',
    appId: '1:347100845168:android:5319a9e2b31f354f6e10b5',
    messagingSenderId: '347100845168',
    projectId: 'yosyelan-a2aae',
    storageBucket: 'yosyelan-a2aae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcrCiqDrc5laR3HDCQcXMmHp8S0zyCDtc',
    appId: '1:347100845168:ios:37dcff3f92ebf96a6e10b5',
    messagingSenderId: '347100845168',
    projectId: 'yosyelan-a2aae',
    storageBucket: 'yosyelan-a2aae.appspot.com',
    iosBundleId: 'com.example.yosyelanInventary',
  );
}
